### ISSUE TITLE
Cannot getEntities asynchronously

### ISSUE THREAD

**Issue by Dg32z** [mcpvp-club/FasterCrystals#20] opened 2024-07-25 13:05 UTC
[21:03:05 ERROR]: Thread Region Scheduler Thread #8 failed main thread check: Cannot getEntities asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:85) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at net.minecraft.world.level.Level.getEntities(Level.java:1579) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1146) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.rayTraceEntities(CraftWorld.java:1198) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.rayTraceEntities(CraftWorld.java:1177) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at xyz.reknown.fastercrystals.listeners.packet.AnimationListener.lambda$onPacketPlayReceive$1(AnimationListener.java:57) ~[[F]FasterCrystals.jar:?]
        at xyz.reknown.fastercrystals.packetevents.impl.util.folia.EntityScheduler.lambda$run$1(EntityScheduler.java:83) ~[[F]FasterCrystals.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:168) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:115) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1649) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:03:05 WARN]: [FasterCrystals] Entity task for FasterCrystals v1.7.0 generated an exception
java.lang.IllegalStateException: Cannot getEntities asynchronously
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:86) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at net.minecraft.world.level.Level.getEntities(Level.java:1579) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1146) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.rayTraceEntities(CraftWorld.java:1198) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.rayTraceEntities(CraftWorld.java:1177) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at xyz.reknown.fastercrystals.listeners.packet.AnimationListener.lambda$onPacketPlayReceive$1(AnimationListener.java:57) ~[[F]FasterCrystals.jar:?]
        at xyz.reknown.fastercrystals.packetevents.impl.util.folia.EntityScheduler.lambda$run$1(EntityScheduler.java:83) ~[[F]FasterCrystals.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:168) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:115) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1649) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"bbd1c34"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

Server:> ver
[21:05:08 INFO]: Checking version, please wait...
[21:05:09 INFO]: This server is running Luminol version git-Luminol-"bbd1c34" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: bbd1c34 on ver/1.20.4)
Unknown version
Previous version: git-Luminol-"9885fe4" (MC: 1.20.4)

**Comment by Jyguy** [comment] 2024-07-25 22:07
@Dg32z Cannot reproduce on git-Folia-"ec6b172" (MC: 1.20.4). Incompatible forks are not supported. Are you able to reproduce on base Folia?

**Comment by Jyguy** [comment] 2024-07-29 02:41
I will close this issue as I cannot reproduce it and no additional information was given. Feel free to reopen if you are able to reproduce it on base Folia.

**Closed by Jyguy** 2024-07-29 02:41 UTC
Labels: bug
